[tool.poetry]
name = "rustyscript"
version = "0.1.0"
description = ""
authors = ["Solaris"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
